name = "santrivora"
main = "src/worker.ts"
compatibility_date = "2024-04-01"
workers_dev = true

[build]
command = ""

# Development environment (default / local)
[[d1_databases]]
binding = "DB"
database_name = "santrivora-db"
database_id = "606a3c63-02e2-44f5-a3f3-b7f069df7499"

[[kv_namespaces]]
binding = "KV"
id = "dce5e0ce216547beb570865b4f2bdb53"
preview_id = "dcfcf5f8604249bdb2201c99b0002278"

[[r2_buckets]]
binding = "R2"
bucket_name = "santrivora-photos"

[vars]
ENVIRONMENT = "development"

# Staging environment
[env.staging]
name = "santrivora-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "santrivora-db-staging"
database_id = "9a916970-7831-458b-b864-87ee117109b1"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "dce5e0ce216547beb570865b4f2bdb53"
preview_id = "dcfcf5f8604249bdb2201c99b0002278"

[[env.staging.r2_buckets]]
binding = "R2"
bucket_name = "santrivora-photos"

# Production environment
[env.production]
name = "santrivora-production"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "santrivora-db"
database_id = "606a3c63-02e2-44f5-a3f3-b7f069df7499"

[[env.production.kv_namespaces]]
binding = "KV"
id = "dce5e0ce216547beb570865b4f2bdb53"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "santrivora-photos"